--- #create soft links
- hosts: test
  user: {{ user }}
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Create symbolic links
      file:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        state: link
      with_items:
        - { src: 'src1', dest: 'dest1' }
        - { src: 'src2', dest: 'dest2' }
        - { src: 'src3', dest: 'dest3' }
